# Do not edit. Generated by the configure script.
export PATH:=/home/penjud/vscode_projects/automation1V2/node/node-v21.7.2/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.10
PREFIX=/home/penjud/node
